### ISSUE TITLE
How to get size of grid at each zoom level

### ISSUE THREAD

**Issue by vk0292** [adammertel/Leaflet.RegularGridCluster#9]
how the size of grid can be calculated in meter or kilometer at every zoom level

**Comment by adammertel** [comment]
Hi vk0292, 
the size of the cell is calculated with this function
`_zoneSize() {    return this.options.zoneSize * Math.pow(2, 10 - this._mapZoom());  },`

please have in mind that the calculation of size is an oversimplification.
Adam

**Comment by vk0292** [comment]
Thanks for reply !
What's the unit of grid size which is calculated from this function whether it is giving area of grid or length ?
for example - I got 16,000 with zone size 1000 and zoom level 6. What is 16000 ? What is its unit ? Is it area or length ?

**Comment by adammertel** [comment]
If I remember correctly, the value is the length of the cell side in meters, but it is valid for the equator regions.

**Comment by vk0292** [comment]
Thanks alot !
Hope its not annoying you! But one more question.
How to display raw data at zoom level 5 rather than 10, it shows raw json data at zoomlevel 10, can it be displayed at 5 zoomlevel ?

**Comment by adammertel** [comment]
No problem - I am glad to help :)
To change the zoom level of the raw elements, try to set the `zoomShowElements` option.
Adam

**Comment by vk0292** [comment]
Thanks alot sir,
Recently I came across an issue , what are different types of method like count and mean?? what does they calculate ? can u tell me all other different method?

**Comment by adammertel** [comment]
Just copy-pasting from the documentation
> method ('count', 'mean', 'median', 'mode', 'min', 'max' and 'sum') - operation how the result value will be calculated from the overlapping elements

**Comment by vk0292** [comment]
Again thank you very much sir!
like the example properties "a" and "b" , i have a property in json say "xyz" whose values are like 0.564356436, 1.860089822, 2.863458341, 4.6452354 etc. ranging from 0 to 5 but its not displayed on selecting method mean or sum, only displayed when i select count. Is it that (feature.properties.a) takes only integer not decimal values?

**Comment by vk0292** [comment]
> Hi vk0292,
> the size of the cell is calculated with this function
> `_zoneSize() { return this.options.zoneSize * Math.pow(2, 10 - this._mapZoom()); },`
> 
> please have in mind that the calculation of size is an oversimplification.
> Adam

can you please tell me what is 10 and 2 in this formula? because i guess formula is returning wrong value.

**Comment by vk0292** [comment]
thanks Adam for help !

**Comment by adammertel** [comment]
@vk0292 I am testing the "mean" method with the `two_datasets` demo and everything looks working
```
markers: {
        radius: {
          method: "mean",
          attribute: "a",
          scale: "continuous",
          range: [-5, 10],
        },
        color: "black",
      },
```

**Comment by adammertel** [comment]
> can you please tell me what is 10 and 2 in this formula? because i guess formula is returning wrong value.
the number 2 is the second exponent and  number 10 is the "default" zoom level
